<!DOCTYPE html>
<html lang="en"><head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <title>$title</title>   
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="generated by dsr2html">
    <meta name="author" content="sebastien stang">
    <link href="static/bootstrap.min.css" rel="stylesheet">
    <link href="static/bootstrap-responsive.min.css" rel="stylesheet">
    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <link rel="shortcut icon" href="static/favicon.ico">
  </head>
  <body>
 
  $content
  
  <script src="static/jquery.min.js"></script>
  <script src="static/bootstrap.min.js"></script>
  <script src="static/jquery.tablesorter.min.js"></script>
  <script src="static/dsr2html.js"></script>

  </body></html>  
  
