<!DOCTYPE html>
<html lang="en"><head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <title>$title</title>   
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="generated by dsr2html">
    <meta name="author" content="sebastien stang">
    <link href="static/bootstrap.min.css" rel="stylesheet">
	<style>
	  body {
	    padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
	  }
	</style>
    <link href="static/bootstrap-responsive.min.css" rel="stylesheet">
    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <link rel="shortcut icon" href="static/favicon.ico">
  </head>
  <body>
  
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="index.html"> $title </a>
         <div class="nav-collapse">
            <ul class="nav">
               <li class="divider-vertical"></li>                                     
            </ul>  	

              <ul class="nav pull-right">
               <li class="divider-vertical"></li>                         
              <!-- <li><a href="#about">About </a></li>  -->
              </ul>    
          </div><!-- /.nav-collapse -->
        </div>
      </div>
    </div>      
  
  <div class="container"> 
  $content
  <footer>
  <hr>
  $perf
  <p class="pull-right"> &copy Sebastien Stang | 2012-2013 </p>
  </footer>      
  </div> 
  
  <script src="static/jquery.min.js"></script>
  <script src="static/bootstrap.min.js"></script>
  <script src="static/jquery.tablesorter.min.js"></script>
  <script src="static/dsr2html.js"></script>

  </body></html>  
  
